name: Keeper-App
on:
  push:
    branches:
      - "master"
jobs:
  build:
    run-on: windows-latest
  
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout
      - uses: actions/checkout@v1

      - name: Install and build
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
      